/**
 * Image helper utilities for responsive optimized image delivery.
 * Abstracts the local build-time optimization approach so components
 * don't need to know about the underlying storage mechanism.
 *
 * Optimized images are generated by scripts/optimize-images.js
 * and stored in public/photos/optimized/{id}-{size}.webp
 */

const SIZES = {
  thumbnail: 400,
  display: 1200,
};

/**
 * Get optimized image URL for a given size.
 * @param {Object} photo - Photo object from photos.json
 * @param {'thumbnail' | 'display' | 'full'} size - Desired image size
 * @returns {string} URL path to the image
 */
export function getImageUrl(photo, size) {
  if (size === 'full') {
    return photo.url;
  }
  return `/photos/optimized/${photo.id}-${size}.webp`;
}

/**
 * Get srcset string for responsive images.
 * @param {Object} photo - Photo object from photos.json
 * @returns {string} srcset attribute value
 */
export function getImageSrcSet(photo) {
  return [
    `${getImageUrl(photo, 'thumbnail')} ${SIZES.thumbnail}w`,
    `${getImageUrl(photo, 'display')} ${SIZES.display}w`,
  ].join(', ');
}

/**
 * Get fallback URL (original file) for error recovery.
 * Used as onError handler to gracefully degrade when optimized images fail.
 * @param {Object} photo - Photo object from photos.json
 * @returns {string} URL path to original image
 */
export function getFallbackUrl(photo) {
  return photo.url;
}

/**
 * Get accessible alt text for a photo.
 * Prefers description over title for richer accessibility context.
 * @param {Object} photo - Photo object from photos.json
 * @returns {string} Alt text
 */
export function getAltText(photo) {
  return photo.description || photo.title;
}
